In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from gensim.models import Word2Vec
from gensim.test.utils import common_texts, get_tmpfile
from gensim.models import KeyedVectors
import re
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv('data/processed_data/messageAll.csv')

In [3]:
len(df)

1192749

In [9]:
!pwd

/home/genex/Notebook


In [114]:
df_list =list(df.message)

In [115]:
#this part is prepared by *-Rabby-*
prepared_data = []
removeChar = '০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯'.split()
for sent in df_list:
    s = re.sub('[^\u0980-\u09ffa-zA-Z?]+', ' ', str(sent))
    for j in removeChar:
        s = s.replace(j, ' ')
    s = ' '.join(s.split())
    if len(s.strip()):
        prepared_data.append(s.lower())
    
print('Total Message', len(prepared_data))

Total Message 912024


In [5]:
prepared_data = []
for sent in df_list:
    prepared_data.append(str(sent).split())

In [87]:
model = Word2Vec(prepared_data,size=1024,window=2,min_count=1,sg=1,workers=4)

In [4]:
model = Word2Vec.load('word2vec_S1024_W2_Min1.model')

In [5]:
model.wv.cosine_similarities(model.wv["cumilla"].reshape(-1),model.wv["comilla"].reshape(1,1024))

array([0.9168761], dtype=float32)

In [8]:
wv.most_similar("achen")

[('asen', 0.977247953414917),
 ('acen', 0.9691460728645325),
 ('asan', 0.9396560788154602),
 ('acho', 0.9198898077011108),
 ('aso', 0.9160470366477966),
 ('acan', 0.9055763483047485),
 ('aco', 0.9044261574745178),
 ('acn', 0.8933955430984497),
 ('asos', 0.885931670665741),
 ('achan', 0.8614093661308289)]

In [156]:
wv['lol']

array([ 0.05484036, -0.02507173,  0.06091474, ..., -0.02009379,
        0.04558235, -0.06747749], dtype=float32)

In [11]:
len(model.wv.vocab.keys())

197468

In [31]:
# model.wv.save("wordvectors.kv")

In [7]:
wv = KeyedVectors.load("wordvectors.kv")

In [50]:
wv['lol']

array([ 0.05484036, -0.02507173,  0.06091474, ..., -0.02009379,
        0.04558235, -0.06747749], dtype=float32)

In [71]:
s = "baler matha ki ajob"

In [72]:
for token in s.split():
    print(token)

baler
matha
ki
ajob


In [73]:
try:
    s = wv['am']
except KeyError:
    print("Not Found")

In [103]:
temp_place = []

In [104]:
temp_place.append(np.zeros(1024,dtype=np.float32))

In [105]:
np.mean(temp_place,axis=0)

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [88]:
np.add(temp_place[0],temp_place[1])

array([ 0.18101002,  0.1143669 , -0.23325801, ..., -0.73187166,
        0.3175489 , -0.09467347], dtype=float32)

In [90]:
np.zeros(1024,dtype=np.float32)

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [102]:
np.mean(temp_place,axis=0)

array([-0.03319152,  0.0924931 ,  0.05806978, ..., -0.23834953,
        0.00162208,  0.02755325], dtype=float32)

In [101]:
np.add([1,1],[1,1])/2

array([1., 1.])

In [131]:
class FeatureExtractor:

    def __init__(self,embedding=None):
        self.wv = wv


    def get_feature_vector_train(self,sentences):

        if self.wv == None:
            raise Exception('Please pass the KeyedVectors object.')

        else:
            sentence_vectors = []
            for sent in sentences:

                temp_placeholder = []
                # temp_placeholder.append(np.zeros(1024,dtype=np.float32))
            
                for token in sent.split():
                    try:
                        temp_placeholder.append(self.wv[token])
                    except KeyError:
                        pass

                if len(temp_placeholder)>0:
                    sentence_vectors.append(np.mean(temp_placeholder,axis=0))

            return np.mean(sentence_vectors,axis=0).reshape(1,-1)


    def get_feature_vector_infer(self,sentence):

        if self.wv == None:
            raise Exception('Please pass flair embedding object.')

        else:
            temp_placeholder = []
            for token in sentence.split():
                try:
                    temp_placeholder.append(self.wv[token])
                except KeyError:
                    pass

            if len(temp_placeholder)>0:
                sent_embd = np.mean(temp_placeholder,axis=0)
                return sent_embd.reshape(1,-1)
            else:
                return np.zeros(1024,dtype=np.float32).reshape(1,-1)

In [132]:
extractor = FeatureExtractor(wv)

In [152]:
query_vec1 = extractor.get_feature_vector_infer("bondho sim er ki offer") 

In [153]:
query_vec2 = extractor.get_feature_vector_infer("ki vat dibo")

In [154]:
cosine_similarity(query_vec1,query_vec2)

array([[0.72017837]], dtype=float32)

In [9]:
!pwd

/home/genex/Notebook
